-- Run this in your Supabase SQL Editor to create the necessary tables

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  industry TEXT,
  ad_account_id TEXT,
  landing_page_url TEXT,
  business_type TEXT DEFAULT 'ecommerce',
  primary_conversion_event TEXT DEFAULT 'conversions',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Safely add columns to existing clients table if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='clients' AND column_name='landing_page_url') THEN
        ALTER TABLE clients ADD COLUMN landing_page_url TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='clients' AND column_name='business_type') THEN
        ALTER TABLE clients ADD COLUMN business_type TEXT DEFAULT 'ecommerce';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='clients' AND column_name='primary_conversion_event') THEN
        ALTER TABLE clients ADD COLUMN primary_conversion_event TEXT DEFAULT 'conversions';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS copy_creatives (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id),
  name TEXT NOT NULL,
  status TEXT DEFAULT 'draft',
  primary_text TEXT,
  headline TEXT,
  description TEXT,
  dna_json TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS copy_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id),
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS image_creatives (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id),
  name TEXT NOT NULL,
  status TEXT DEFAULT 'draft',
  creative_id TEXT,
  visual_type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS image_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_id BIGINT REFERENCES image_creatives(id),
  ratio TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS meta_settings (
  id BIGINT PRIMARY KEY,
  ad_account_id TEXT,
  access_token TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Safely add columns to existing meta_settings table if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='meta_settings' AND column_name='access_token') THEN
        ALTER TABLE meta_settings ADD COLUMN access_token TEXT;
    END IF;
    
    -- Make ad_account_id nullable if it isn't already
    ALTER TABLE meta_settings ALTER COLUMN ad_account_id DROP NOT NULL;
END $$;

CREATE TABLE IF NOT EXISTS ad_performance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id),
  meta_ad_id TEXT NOT NULL,
  ad_name TEXT NOT NULL,
  creative_id TEXT,
  campaign_id TEXT,
  adset_id TEXT,
  metrics_json TEXT NOT NULL,
  date_start TEXT NOT NULL,
  date_stop TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(meta_ad_id, date_start, date_stop)
);

CREATE TABLE IF NOT EXISTS column_presets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  columns_json TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS client_conversion_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id),
  event_type TEXT NOT NULL,
  metric_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(client_id, event_type)
);

CREATE TABLE IF NOT EXISTS creative_dna (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meta_ad_id TEXT NOT NULL UNIQUE,
  visual_style TEXT,
  primary_subject TEXT,
  people_present BOOLEAN,
  age_group_estimate TEXT,
  facial_expression TEXT,
  text_overlay_present BOOLEAN,
  visual_text_content TEXT,
  cta_button_present BOOLEAN,
  cta_button_text TEXT,
  cta_button_color TEXT,
  primary_color TEXT,
  background_color TEXT,
  layout_type TEXT,
  text_density TEXT,
  graphic_elements_json TEXT,
  visual_complexity_score INTEGER,
  headline_text TEXT,
  headline_length INTEGER,
  headline_structure TEXT,
  primary_text_length INTEGER,
  copy_structure TEXT,
  emotional_trigger TEXT,
  offer_type TEXT,
  cta_language TEXT,
  copy_complexity_score INTEGER,
  psychological_triggers_json TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS kpi_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) UNIQUE,
  primary_kpi TEXT DEFAULT 'roas',
  weights_json TEXT NOT NULL,
  metric_mappings_json TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS ad_breakdowns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id),
  meta_ad_id TEXT NOT NULL,
  breakdown_type TEXT NOT NULL,
  breakdown_value TEXT NOT NULL,
  metrics_json TEXT NOT NULL,
  date_start TEXT NOT NULL,
  date_stop TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(meta_ad_id, breakdown_type, breakdown_value, date_start, date_stop)
);

CREATE TABLE IF NOT EXISTS creative_dna_advanced (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meta_ad_id TEXT NOT NULL UNIQUE,
  campaign_id TEXT,
  adset_id TEXT,
  creative_id TEXT,
  visual_type TEXT,
  visual_style TEXT,
  objects_present_json TEXT,
  people_present BOOLEAN,
  age_group_estimate TEXT,
  gender_presentation TEXT,
  facial_expression TEXT,
  product_presence BOOLEAN,
  logo_presence BOOLEAN,
  text_overlay_present BOOLEAN,
  text_overlay_density TEXT,
  text_overlay_positioning TEXT,
  in_graphic_cta_present BOOLEAN,
  in_graphic_cta_text TEXT,
  in_graphic_cta_color TEXT,
  button_shape TEXT,
  dominant_colors_json TEXT,
  color_palette TEXT,
  background_style TEXT,
  contrast_level TEXT,
  layout_structure TEXT,
  camera_framing TEXT,
  visual_complexity_score INTEGER,
  primary_text_dna_json TEXT,
  headline_dna_json TEXT,
  description_dna_json TEXT,
  emotional_triggers TEXT,
  copy_hook_type TEXT,
  copy_length_category TEXT,
  pacing_style TEXT,
  detected_objects TEXT,
  brand_presence_score INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS performance_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id),
  date_range_start TEXT NOT NULL,
  date_range_end TEXT NOT NULL,
  report_json TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
